export class ProgramacionAnualModel{

  static ProgramacionAnualModelFromJson(obj : Object){
    return new ProgramacionAnualModel(
      

      obj['intIdActividad'],
      obj['intIdEquipo'],
      obj['intCondicionSistema'],
      obj['intCondicionEquipo'],
      obj['intIdResponsable'],
      
      obj['intEstado'],
      
      obj['strNombreActividad'],
      obj['strNombreEquipo'],
      obj['strNombreTipoMant'],
      obj['strNombreParte'],
      obj['strNombreSubParte'],
      obj['strCodUbicacionTecnica'],
      obj['strCodEquipo'],
  
      obj['int_1'],
       obj['int_2'],
       obj['int_3'],
       obj['int_4'],
       obj['int_5'],
       obj['int_6'],
       obj['int_7'],
       obj['int_8'],
       obj['int_9'],
       obj['int_10'],
       obj['int_11'],
       obj['int_12'],
       obj['int_13'],
       obj['int_14'],
       obj['int_15'],
       obj['int_16'],
       obj['int_17'],
       obj['int_18'],
       obj['int_19'],
       obj['int_20'],
       obj['int_21'],
       obj['int_22'],
       obj['int_23'],
       obj['int_24'],
       obj['int_25'],
       obj['int_26'],
       obj['int_27'],
       obj['int_28'],
       obj['int_29'],
       obj['int_30'],
       obj['int_31'],
       obj['int_32'],
       obj['int_33'],
       obj['int_34'],
       obj['int_35'],
       obj['int_36'],
       obj['int_37'],
       obj['int_38'],
       obj['int_39'],
       obj['int_40'],
       obj['int_41'],
       obj['int_42'],
       obj['int_43'],
       obj['int_44'],
       obj['int_45'],
       obj['int_46'],
       obj['int_47'],
       obj['int_48'],
       obj['int_49'],
       obj['int_50'],
       obj['int_51'],
       obj['int_52'],
       obj['int_53'],


    );

   }
    
    constructor(
        intIdActividad: number,
        intIdEquipo: number,
        intCondicionSistema: number,
        intCondicionEquipo: number,
        intIdResponsable: number,
        //intBloqueo: number,
        intEstado: number,
        //intIdTipoMant : number,
        //intIdParte : number,
        //intIdSubparte : number,
        strNombreActividad : string,
        strNombreEquipo : string,
        strNombreTipoMant : string,
        strNombreParte : string,
        strNombreSubParte : string,
        strCodUbicacionTecnica : string,
        strCodEquipo : string,
    
        int_1  : number,
         int_2  : number,
         int_3  : number,
         int_4  : number,
         int_5  : number,
         int_6  : number,
         int_7  : number,
         int_8  : number,
         int_9  : number,
         int_10 : number,
         int_11 : number,
         int_12 : number,
         int_13 : number,
         int_14 : number,
         int_15 : number,
         int_16 : number,
         int_17 : number,
         int_18 : number,
         int_19 : number,
         int_20 : number,
         int_21 : number,
         int_22 : number,
         int_23 : number,
         int_24 : number,
         int_25 : number,
         int_26 : number,
         int_27 : number,
         int_28 : number,
         int_29 : number,
         int_30 : number,
         int_31 : number,
    
         int_32 : number,
         int_33 : number,
         int_34 : number,
         int_35 : number,
         int_36 : number,
         int_37 : number,
         int_38 : number,
         int_39 : number,
         int_40 : number,
         int_41 : number,
         int_42 : number,
         int_43 : number,
    
         int_44 : number,
         int_45 : number,
         int_46 : number,
         int_47 : number,
         int_48 : number,
         int_49 : number,
         int_50 : number,
         int_51 : number,
         int_52 : number,
         int_53 : number,
           ){}

}